// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXctDcPC-bu8_KE4nLFWCOT17SGMpTtms',
    appId: '1:632194183405:web:0968422b409b8048e39ce4',
    messagingSenderId: '632194183405',
    projectId: 'newapp-a7188',
    authDomain: 'newapp-a7188.firebaseapp.com',
    storageBucket: 'newapp-a7188.appspot.com',
    measurementId: 'G-81HHQZMCFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClaDNwX8AqF_qOvywdWqkUKhr55Z277IU',
    appId: '1:632194183405:android:26ddc95a8790dc26e39ce4',
    messagingSenderId: '632194183405',
    projectId: 'newapp-a7188',
    storageBucket: 'newapp-a7188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNv_9Mp30OjTiHWcjqiWAmoNEe5WOmlS8',
    appId: '1:632194183405:ios:9f1b8abb257315fde39ce4',
    messagingSenderId: '632194183405',
    projectId: 'newapp-a7188',
    storageBucket: 'newapp-a7188.appspot.com',
    iosBundleId: 'com.firebaseapplication.firebaseapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNv_9Mp30OjTiHWcjqiWAmoNEe5WOmlS8',
    appId: '1:632194183405:ios:9f1b8abb257315fde39ce4',
    messagingSenderId: '632194183405',
    projectId: 'newapp-a7188',
    storageBucket: 'newapp-a7188.appspot.com',
    iosBundleId: 'com.firebaseapplication.firebaseapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXctDcPC-bu8_KE4nLFWCOT17SGMpTtms',
    appId: '1:632194183405:web:74f7faac3d6c17d2e39ce4',
    messagingSenderId: '632194183405',
    projectId: 'newapp-a7188',
    authDomain: 'newapp-a7188.firebaseapp.com',
    storageBucket: 'newapp-a7188.appspot.com',
    measurementId: 'G-BGYRZN1TBX',
  );

}